#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <boost/beast/ssl/ssl_stream.hpp>
#include <boost/exception/diagnostic_information.hpp>
#include <jde/framework.h>
#include <jde/web/usings.h>
#include <jde/framework/coroutine/Task.h>
#include "../../../../Framework/source/coroutine/Awaitable.h"
#include <jde/app/shared/exports.h>
#include <jde/app/shared/proto/App.FromServer.pb.h>
#include <jde/framework/io/proto.h>
#include "../../../../Framework/source/threading/InterruptibleThread.h"
#include "../../../../Framework/source/DateTime.h"
