#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <boost/beast/ssl/ssl_stream.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <open62541/common.h>
#include <open62541/types.h>
#include <open62541/server.h>
#include <jde/framework.h>
#include <jde/framework/str.h>
#include <jde/framework/settings.h>
#include <jde/framework/coroutine/Await.h>
#include <jde/framework/chrono.h>
#include <jde/db/Row.h>
#include <jde/db/IDataSource.h>
#include <jde/db/awaits/SelectAwait.h>
#include <jde/db/generators/Functions.h>
#include <jde/db/meta/AppSchema.h>
#include <jde/app/shared/exports.h>
#include <jde/opc/exports.h>
#include <jde/opc/uatypes/helpers.h>
#include <jde/opc/uatypes/Node.h>
#include <jde/opc/uatypes/UAException.h>
#include "usings.h"
#include "globals.h"