#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <boost/beast/ssl/ssl_stream.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <open62541/common.h>
#include <open62541/types.h>
#include <open62541/server.h>
#include <jde/framework.h>
#include <jde/framework/str.h>
#include <jde/framework/settings.h>
#include <jde/framework/coroutine/Await.h>
#include "../../Framework/source/DateTime.h"
#include <jde/db/IRow.h>
#include <jde/db/IDataSource.h>
#include <jde/db/awaits/SelectAwait.h>
#include <jde/app/shared/exports.h>
#include <jde/opc/exports.h>
#include <jde/opc/uatypes/helpers.h>
#include <jde/opc/uatypes/Node.h>
#include <jde/opc/uatypes/UAException.h>
#include "globals.h"
#include "../../../libs/opc/src/types/proto/Opc.Common.pb.h"
