#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <boost/beast/ssl/ssl_stream.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <open62541/common.h>
#include <open62541/types.h>
#include <open62541/server.h>
#include <jde/fwk.h>
#include <jde/fwk/str.h>
#include <jde/fwk/settings.h>
#include <jde/fwk/co/Await.h>
#include <jde/fwk/chrono.h>
#include <jde/db/Row.h>
#include <jde/db/IDataSource.h>
#include <jde/db/awaits/SelectAwait.h>
#include <jde/db/generators/Functions.h>
#include <jde/db/meta/AppSchema.h>
#include <jde/app/shared/exports.h>
#include <jde/opc/exports.h>
#include <jde/opc/uatypes/opcHelpers.h>
#include <jde/opc/uatypes/NodeId.h>
#include <jde/opc/uatypes/ExNodeId.h>
#include <jde/opc/UAException.h>
#include "usings.h"
#include "globals.h"