#include <jde/TypeDefs.h>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/crc.hpp>
#include <boost/system/error_code.hpp>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/fmt/ostr.h>
#include <nlohmann/json.hpp>
#include <jde/io/tinyxml2.h>
#include <jde/Log.h>
#include <jde/Str.h>
