#pragma once
#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <boost/asio/strand.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/beast/ssl/ssl_stream.hpp>
#include <boost/beast/websocket/stream.hpp>
#include <boost/exception/diagnostic_information.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/unordered/concurrent_flat_map.hpp>
#include <boost/unordered/concurrent_flat_set.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <open62541/client_config_default.h>
#include <open62541/client_highlevel.h>
#include <open62541/client_highlevel_async.h>
#include <open62541/plugin/log_stdout.h>
#include <open62541/client_subscriptions.h>
#include <jde/framework.h>
#include <jde/framework/coroutine/Await.h>
#include <jde/crypto/OpenSsl.h>
#include <jde/access/usings.h>
#include <jde/web/client/exports.h>
#include <jde/web/client/proto/Web.FromServer.pb.h>
#include <jde/app/shared/exports.h>
#include <jde/app/shared/proto/App.FromClient.pb.h>
#include <jde/app/shared/proto/App.FromClient.pb.h>
#include <jde/app/shared/proto/App.FromServer.pb.h>
#include <jde/app/shared/exports.h>
#include <jde/app/shared/proto/Common.pb.h>
#include <jde/opc/exports.h>
#include <jde/opc/usings.h>
#include <jde/opc/uatypes/Node.h>
#include <jde/opc/uatypes/Logger.h>
#include "uatypes/UAClientException.h"
DISABLE_WARNINGS
#include "types/proto/Opc.Common.pb.h"
#include "types/proto/Opc.FromServer.pb.h"
#include "types/proto/Opc.FromClient.pb.h"
ENABLE_WARNINGS