#include <sqlite3.h>
#include <gtest/gtest.h>
#include <jde/fwk.h>
#include <jde/fwk/str.h>
#include <jde/fwk/io/json.h>
#include <jde/fwk/chrono.h>
#include "jde/db/db.h"
#include <jde/db/IDataSource.h>
#include "../src/usings.h"
#include "globals.h"
